# Generated by Django 5.0.6 on 2024-06-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_friendrequest_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
