# Generated by Django 5.0.6 on 2024-06-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_tournament_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_connection',
            field=models.BooleanField(default=True),
        ),
    ]
